CREATE TABLE IF NOT EXISTS `payment` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `payment_gateway` varchar(50) NOT NULL DEFAULT '' COMMENT '결제 대행사 (DIRECT_CREDIT_CARD, TOSS_PAY, KAKAO_PAY)',
  `reservation_id` int(11) NOT NULL DEFAULT 0,
  `reservation_no` varchar(50) DEFAULT '' COMMENT '고객 제공 예약 ID',
  `payment_key` varchar(100) DEFAULT '' COMMENT '결제 키',
  `order_name` varchar(100) DEFAULT NULL COMMENT '상품 이름',
  `arrival_date` datetime DEFAULT NULL COMMENT '숙박 시작일',
  `departure_date` datetime DEFAULT NULL COMMENT '숙박 마지막일',
  `easy_pay` varchar(30) DEFAULT NULL COMMENT '간편 결제 수단 (토스결제, 페이코, 삼성페이)',
  `method` varchar(100) DEFAULT NULL COMMENT '결제 수단 (카드, 가상계좌, 휴대폰, 계좌이체, 상품권(문화상품권, 도서문화상품권, 게임문화상품권))',
  `total_amount` int(11) NOT NULL DEFAULT 0 COMMENT '총 결제금액',
  `tax_free_amount` int(11) NOT NULL DEFAULT 0 COMMENT '비과세 금액',
  `canceled_amount` int(11) NOT NULL DEFAULT 0 COMMENT '취소된 금액',
  `discount_amount` int(11) NOT NULL DEFAULT 0 COMMENT '카드사 즉시할인 프로모션 적용 금액',
  `card_company` varchar(20) DEFAULT NULL COMMENT '카드사 이름',
  `card_number` varchar(25) DEFAULT NULL COMMENT '카드 번호',
  `card_installment_plan_months` int(11) DEFAULT NULL COMMENT '카드 할부 개월 수 (0: 일시불)',
  `card_approve_no` varchar(25) DEFAULT NULL COMMENT '카드사 승인 번호',
  `card_type` varchar(20) DEFAULT NULL COMMENT '카드 종류 (신용, 체크, 기프트)',
  `card_owner_type` varchar(20) DEFAULT NULL COMMENT '카드 소유자 타입 (개인, 법인)',
  `card_ receipt_url` varchar(200) DEFAULT NULL COMMENT '카드 매출전표 조회 페이지 주소',
  `is_insterest_free` tinyint(1) DEFAULT NULL COMMENT '카드 무이자 할부 적용 여부',
  `card_ acquire_status` varchar(20) DEFAULT NULL COMMENT '카드 결제 매입 상태 (READY, REQUESTED, COMPLETED, CANCEL_REQUESTED, CANCELED)',
  `request_date` datetime DEFAULT NULL COMMENT '결제 요청 날짜',
  `approve_date` datetime DEFAULT NULL COMMENT '결제 승인 날짜',
  `cancel_date` datetime DEFAULT NULL COMMENT '결제 취소 날짜',
  `update_date` datetime DEFAULT NULL COMMENT '결제 업데이트 날짜',
  PRIMARY KEY (`id`),
  UNIQUE KEY `payment_index1` (`reservation_id`,`reservation_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='주문 결제 정보 테이블';