//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ButlerLee.API.Models.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ButlerLee.API.Models.Exceptions.ErrorCodes", typeof(ErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 반드시 성인 1인 이상 포함 하여 예약해주세요..
        /// </summary>
        public static string ADULTS_IS_NULL {
            get {
                return ResourceManager.GetString("ADULTS_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 취소된 예약 입니다..
        /// </summary>
        public static string ALREADY_CANCELED_RESERVATION {
            get {
                return ResourceManager.GetString("ALREADY_CANCELED_RESERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 결제된 예약 입니다..
        /// </summary>
        public static string ALREADY_PAID_RESERVATION {
            get {
                return ResourceManager.GetString("ALREADY_PAID_RESERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 취소 사유가 입력되지 않았습니다. 확인 후 다시 시도하십시요..
        /// </summary>
        public static string CANCEL_REASON_IS_NULL {
            get {
                return ResourceManager.GetString("CANCEL_REASON_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 예약 날짜가 올바르지 않습니다. 확인 후 다시 시도하십시요..
        /// </summary>
        public static string DATE_IS_INVALID {
            get {
                return ResourceManager.GetString("DATE_IS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 일반카드결제(호스트어웨이) DB 업데이트 및 생성이 실패했습니다..
        /// </summary>
        public static string HOST_AWAY_CARD_PAYMENT_FAIL {
            get {
                return ResourceManager.GetString("HOST_AWAY_CARD_PAYMENT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버에서 오류가 발생되었습니다..
        /// </summary>
        public static string INTERNAL_SERVER_ERROR {
            get {
                return ResourceManager.GetString("INTERNAL_SERVER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 카드정보가 올바르게 입력되지 않았습니다. 확인 후 다시 시도하십시요..
        /// </summary>
        public static string INVALID_CREDIT_CARD {
            get {
                return ResourceManager.GetString("INVALID_CREDIT_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 숙소가 존재하지 않습니다..
        /// </summary>
        public static string LISTING_NOT_FOUND {
            get {
                return ResourceManager.GetString("LISTING_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 테스트용 객실이 아닙니다..
        /// </summary>
        public static string NOT_TEST_LISTING {
            get {
                return ResourceManager.GetString("NOT_TEST_LISTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 변수가 입력되지 않았습니다. 변수를 입력해주세요..
        /// </summary>
        public static string PARAMETER_OBJECT_IS_NULL {
            get {
                return ResourceManager.GetString("PARAMETER_OBJECT_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 고객이 결제를 취소했습니다..
        /// </summary>
        public static string PAYMENT_CANCELED_BY_CUSTOMER {
            get {
                return ResourceManager.GetString("PAYMENT_CANCELED_BY_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Content 변수가 입력되지 않았습니다. 변수를 입력해주세요..
        /// </summary>
        public static string PAYMENT_IS_NULL {
            get {
                return ResourceManager.GetString("PAYMENT_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentMethod에 대한 변수가 입력되지 않았습니다. 확인 후 다시 시도하십시요..
        /// </summary>
        public static string PAYMENT_METHOD_IS_NULL {
            get {
                return ResourceManager.GetString("PAYMENT_METHOD_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 결제정보가 존재하지 않습니다..
        /// </summary>
        public static string PAYMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PAYMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 결제 정보가 이미 존재합니다..
        /// </summary>
        public static string PAYMET_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("PAYMET_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 요청이 잘못되었습니다. 확인 후 다시 시도하십시요..
        /// </summary>
        public static string REQUEST_IS_INVALID {
            get {
                return ResourceManager.GetString("REQUEST_IS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 필수 데이터가 충족되지 않습니다. 확인 후 다시 시도하십시요..
        /// </summary>
        public static string REQUIRED_DATA_IS_NOT_SATISFIED {
            get {
                return ResourceManager.GetString("REQUIRED_DATA_IS_NOT_SATISFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 필요한 변수가 전부 입력되었는지 확인해 주세요..
        /// </summary>
        public static string REQUIRED_PRARMETER_IS_NULL {
            get {
                return ResourceManager.GetString("REQUIRED_PRARMETER_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 예약이 존재하지 않습니다..
        /// </summary>
        public static string RESERVATION_NOT_FOUND {
            get {
                return ResourceManager.GetString("RESERVATION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 객실 수용 가능인원을 초과하였습니다. 인원 조정후 다시 시도해 주세요..
        /// </summary>
        public static string ROOM_CAPACITY_HAS_EXCEEDED {
            get {
                return ResourceManager.GetString("ROOM_CAPACITY_HAS_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 결제 요청시간이 초과되었습니다. 다시 결제를 시도해주세요..
        /// </summary>
        public static string TIME_OUT_FOR_PAYMENT_REQUEST {
            get {
                return ResourceManager.GetString("TIME_OUT_FOR_PAYMENT_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orderId Type Error! SDK 호출 시 orderId에 예약ID(int)를 기입해주세요..
        /// </summary>
        public static string TOSS_ORDER_ID_IS_WRONG {
            get {
                return ResourceManager.GetString("TOSS_ORDER_ID_IS_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to totalPrice가 서버와 일치하지 않습니다. 확인 후 다시 시도하십시요..
        /// </summary>
        public static string TOTAL_PRICE_IS_INVALID {
            get {
                return ResourceManager.GetString("TOTAL_PRICE_IS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 죄송합니다. 이용불가능한 지점입니다. 다른 지점을 예약해주세요..
        /// </summary>
        public static string UNAVAILABLE_LISTING {
            get {
                return ResourceManager.GetString("UNAVAILABLE_LISTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 죄송합니다. 해당 날짜에 예약이 가능하지 않습니다..
        /// </summary>
        public static string UNBOOKABLE_LISTING {
            get {
                return ResourceManager.GetString("UNBOOKABLE_LISTING", resourceCulture);
            }
        }
    }
}
